### ISSUE TITLE
Make camera better

### ISSUE THREAD

**Issue by cbebry** [ZFGCCP/kot-mono#25]
It's so easy to get off the screen with Link. I would think that the camera should always include Link.

**Comment by MGZero** [comment]
What branch is this on?

**Comment by cbebry** [comment]
NCFC that might be why?

**Comment by MGZero** [comment]
No I was expecting it to be elsewhere.  Can you give steps to reproduce?

**Comment by cbebry** [comment]
I basically just move off screen using WADS keys. I have attached GIF of this occurring.
![kot-camera-issue](https://cloud.githubusercontent.com/assets/3312895/8690206/66040bd6-2a7f-11e5-86b1-6d54350aff05.gif)

**Comment by MGZero** [comment]
Not able to reproduce on another Windows machine.  Might be a Linux-specific issue or a Monogame bug.

**Comment by MGZero** [comment]
Interesting to note that the player is actually moving faster than the camera here as well as the fact that the camera moves before the player even leaves the boundary (about 80 pixels from the left and right of the screen and 100 from the top and bottom)

**Comment by cbebry** [comment]
I wonder what could be different and what would cause that. If you want to add more debug information and have me re-run it again I will gladly do that.

**Comment by MGZero** [comment]
Yea, this will be difficult for me to debug and fix due to my environment so I'll have to do that.  However, I'm not planning on releasing a Linux binary for NCFC so it can wait until after.
